spring:
  datasource:
    name: aws-postgres
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://pariscodeacademy.cnesgewpdnmj.eu-west-3.rds.amazonaws.com/dbtest"
    password: 123456A_
    username: codeacademy
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    show-sql: true