spring:
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017

#  datasource:
#    name: aws-postgres
#    driver-class-name: org.postgresql.Driver
#    url: "jdbc:postgresql://LONC02SF0LNG8WL:5432/dbtest"
#    password: 123456A_
#    username: codeacademy
#    type: org.apache.tomcat.jdbc.pool.DataSource
#  jpa:
#    show-sql: true
#logging:
#  level:
#    org.springframework.transaction.interceptor=TRACE